







###  Enregistrement

POST  http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "username": "john",
  "email": "jeancympoy24@gmail.com",
  "password": "123456",
  "clinicId": "65f1c2e8a1b23c0012345678",
  "gender": "male",
  "tel": "0999999999",
  "country": "DRC",
  "city": "Kinshasa"
}

###  login

POST https://africaacademy-server.onrender.com/api/v1/auth/login
Content-Type: application/json

{
  "email": "jeancympoyie@gmail.com",
  "password": "123456"
}

### Change Mot de Passwoerd

PUT  http://localhost:5000/api/v1/auth/update-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGNkMjM3ZjljOTYxZTFhNDdjNjFlNzEiLCJlbWFpbCI6ImplYW5jeW1wb3kyNEBnbWFpbC5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNzU4Mjc1Mjk1LCJleHAiOjE3NTgyNzYxOTV9.ge9XwheHD_PeZKNbjTkAIi6KYAoSfFn9yva-pdiB-EM

{ 
    "currentPassword":"1234",
    "newPassword":"0000"

}
###

###  request code

POST http://localhost:5000/api/v1/auth/request-code
Content-Type: application/json

{ 
  "email": "jeancympoyie@gmail.com"

}
###  request Password

POST http://localhost:5000/api/v1/auth/reset-password
Content-Type: application/json

{ 

  "email": "jeancympoy24@gmail.com",
  "code": "465917",
  "newPassword":"1234"

}

### Verify
POST http://localhost:5000/api/v1/auth/verify-otp
Content-Type: application/json

{
  "email":"jeancympoyie@gmail.com",
  "otpCode":"4031"
}

### Profiles

GET  http://localhost:5000/api/v1/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGNkMjM3ZjljOTYxZTFhNDdjNjFlNzEiLCJlbWFpbCI6ImplYW5jeW1wb3kyNEBnbWFpbC5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNzU4Mjc1Mjk1LCJleHAiOjE3NTgyNzYxOTV9.ge9XwheHD_PeZKNbjTkAIi6KYAoSfFn9yva-pdiB-EM

###


### UPdate Profiles

PUT   http://localhost:5000/api/v1/auth/update-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGNkMjM3ZjljOTYxZTFhNDdjNjFlNzEiLCJlbWFpbCI6ImplYW5jeW1wb3kyNEBnbWFpbC5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNzU4Mjc1Mjk1LCJleHAiOjE3NTgyNzYxOTV9.ge9XwheHD_PeZKNbjTkAIi6KYAoSfFn9yva-pdiB-EM

{
  "nom": "Mpoyi",
  "prenom": "Jeancy",
  "email": "jeancympoy24@gmail.com",
  "tel": "243848849332",
  "address": [
    {
      "ville": "Kinshasa",
      "pays": "Congo"
    }
  ]
}


### UPdate Profiles

POST    http://localhost:5000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGNkMjM3ZjljOTYxZTFhNDdjNjFlNzEiLCJlbWFpbCI6ImplYW5jeW1wb3kyNEBnbWFpbC5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNzU4Mjc1Mjk1LCJleHAiOjE3NTgyNzYxOTV9.ge9XwheHD_PeZKNbjTkAIi6KYAoSfFn9yva-pdiB-EM



### UPdate Profiles

DELETE     http://localhost:5000/api/v1/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGNkMjM3ZjljOTYxZTFhNDdjNjFlNzEiLCJlbWFpbCI6ImplYW5jeW1wb3kyNEBnbWFpbC5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNzU4Mjc1Mjk1LCJleHAiOjE3NTgyNzYxOTV9.ge9XwheHD_PeZKNbjTkAIi6KYAoSfFn9yva-pdiB-EM


###


POST http://localhost:5000/api/v1/clinic/appointment/en1rcy4q
Content-Type: application/json

{
  "motif": "Dental checkup",
  "date": "2026-04-10T10:00:00.000Z",
  "guest": {
    "name": "John Doe",
    "email": "john@example.com",
    "phone": "+243812345678"
  }
}

