@baseUrl = http://localhost:5000/api/v1/clinic
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ2MTZmYTA0ZGJjYmZmODU4NTVmMmMiLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6InRyYWluaW5ndGVjaDg0QGdtYWlsLmNvbSIsImNsaW5pY0lkIjoiZW4xcmN5NHEiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzc1NzI3ODU1LCJleHAiOjE3NzU3Mjg3NTV9.XBRfhMaI0gJZ5_cMxS0PW9_GnkFOKOXoLKez1F4UDdQ
@doctorId =69d76574ddcbb637c41bcf18

### CREATE DOCTOR
POST {{baseUrl}}/doctor
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dr John Smith",
  "email": "john.smith@clinic.com",
  "phone": "+243999999999",
  "specialty": "Cardiology",
  "available": true,
  "availableMedicines": ["Paracetamol", "Aspirin"]
}

### GET DOCTORS
GET {{baseUrl}}/doctor/doctors
Content-Type: application/json
Authorization: Bearer {{token}}

### GET SINGLE
GET {{baseUrl}}/doctor/{{doctorId}}
Authorization: Bearer {{token}}

### UPDATE
PUT {{baseUrl}}/doctor/{{doctorId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated Name"
}

### DELETE
DELETE {{baseUrl}}/doctor/{{doctorId}}
Authorization: Bearer {{token}}